// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/shortener/shortener.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на сокращение URL (текстовый формат)
type ShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Передается через metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLRequest) Reset() {
	*x = ShortenURLRequest{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRequest) ProtoMessage() {}

func (x *ShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ShortenURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Ответ на сокращение URL (текстовый формат)
type ShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResponse) Reset() {
	*x = ShortenURLResponse{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResponse) ProtoMessage() {}

func (x *ShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// Запрос на сокращение URL (JSON формат)
type ShortenURLJSONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Передается через metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLJSONRequest) Reset() {
	*x = ShortenURLJSONRequest{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLJSONRequest) ProtoMessage() {}

func (x *ShortenURLJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLJSONRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLJSONRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenURLJSONRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ShortenURLJSONRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Ответ на сокращение URL (JSON формат)
type ShortenURLJSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLJSONResponse) Reset() {
	*x = ShortenURLJSONResponse{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLJSONResponse) ProtoMessage() {}

func (x *ShortenURLJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLJSONResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLJSONResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ShortenURLJSONResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// Запрос на получение оригинального URL
type ExpandURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortId       string                 `protobuf:"bytes,1,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandURLRequest) Reset() {
	*x = ExpandURLRequest{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandURLRequest) ProtoMessage() {}

func (x *ExpandURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandURLRequest.ProtoReflect.Descriptor instead.
func (*ExpandURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *ExpandURLRequest) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

// Ответ на получение оригинального URL
type ExpandURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandURLResponse) Reset() {
	*x = ExpandURLResponse{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandURLResponse) ProtoMessage() {}

func (x *ExpandURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandURLResponse.ProtoReflect.Descriptor instead.
func (*ExpandURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *ExpandURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// Элемент пакетного запроса
type BatchShortenItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortenItem) Reset() {
	*x = BatchShortenItem{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenItem) ProtoMessage() {}

func (x *BatchShortenItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenItem.ProtoReflect.Descriptor instead.
func (*BatchShortenItem) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *BatchShortenItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchShortenItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// Элемент пакетного ответа
type BatchShortenResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortenResponseItem) Reset() {
	*x = BatchShortenResponseItem{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortenResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortenResponseItem) ProtoMessage() {}

func (x *BatchShortenResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortenResponseItem.ProtoReflect.Descriptor instead.
func (*BatchShortenResponseItem) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *BatchShortenResponseItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchShortenResponseItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// Запрос на пакетное сокращение URL
type ShortenBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchShortenItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Передается через metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchRequest) Reset() {
	*x = ShortenBatchRequest{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchRequest) ProtoMessage() {}

func (x *ShortenBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortenBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *ShortenBatchRequest) GetItems() []*BatchShortenItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShortenBatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Ответ на пакетное сокращение URL
type ShortenBatchResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*BatchShortenResponseItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResponse) Reset() {
	*x = ShortenBatchResponse{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponse) ProtoMessage() {}

func (x *ShortenBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *ShortenBatchResponse) GetItems() []*BatchShortenResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// URL пользователя
type UserURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURL) Reset() {
	*x = UserURL{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURL) ProtoMessage() {}

func (x *UserURL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURL.ProtoReflect.Descriptor instead.
func (*UserURL) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *UserURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// Запрос на получение URL пользователя
type GetUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Передается через metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsRequest) Reset() {
	*x = GetUserURLsRequest{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsRequest) ProtoMessage() {}

func (x *GetUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsRequest.ProtoReflect.Descriptor instead.
func (*GetUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserURLsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Ответ на получение URL пользователя
type GetUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UserURL             `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsResponse) Reset() {
	*x = GetUserURLsResponse{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsResponse) ProtoMessage() {}

func (x *GetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserURLsResponse) GetUrls() []*UserURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

// Запрос на удаление URL пользователя
type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortIds      []string               `protobuf:"bytes,1,rep,name=short_ids,json=shortIds,proto3" json:"short_ids,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Передается через metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteUserURLsRequest) GetShortIds() []string {
	if x != nil {
		return x.ShortIds
	}
	return nil
}

func (x *DeleteUserURLsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Ответ на удаление URL пользователя
type DeleteUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsResponse) Reset() {
	*x = DeleteUserURLsResponse{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsResponse) ProtoMessage() {}

func (x *DeleteUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUserURLsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Запрос на проверку работоспособности
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{15}
}

// Ответ на проверку работоспособности
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{16}
}

func (x *PingResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

// Запрос на получение статистики
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{17}
}

// Ответ на получение статистики
type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`   // количество сокращённых URL в сервисе
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"` // количество пользователей в сервисе
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_shortener_shortener_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_shortener_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_shortener_proto_rawDescGZIP(), []int{18}
}

func (x *GetStatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetStatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_proto_shortener_shortener_proto protoreflect.FileDescriptor

const file_proto_shortener_shortener_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/shortener/shortener.proto\x12\tshortener\">\n" +
	"\x11ShortenURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x12ShortenURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"B\n" +
	"\x15ShortenURLJSONRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"0\n" +
	"\x16ShortenURLJSONResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"-\n" +
	"\x10ExpandURLRequest\x12\x19\n" +
	"\bshort_id\x18\x01 \x01(\tR\ashortId\"6\n" +
	"\x11ExpandURLResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"\\\n" +
	"\x10BatchShortenItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"^\n" +
	"\x18BatchShortenResponseItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"a\n" +
	"\x13ShortenBatchRequest\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.shortener.BatchShortenItemR\x05items\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"Q\n" +
	"\x14ShortenBatchResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.shortener.BatchShortenResponseItemR\x05items\"I\n" +
	"\aUserURL\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"-\n" +
	"\x12GetUserURLsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x13GetUserURLsResponse\x12&\n" +
	"\x04urls\x18\x01 \x03(\v2\x12.shortener.UserURLR\x04urls\"M\n" +
	"\x15DeleteUserURLsRequest\x12\x1b\n" +
	"\tshort_ids\x18\x01 \x03(\tR\bshortIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"2\n" +
	"\x16DeleteUserURLsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\"\x11\n" +
	"\x0fGetStatsRequest\"<\n" +
	"\x10GetStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users2\xec\x04\n" +
	"\fURLShortener\x12I\n" +
	"\n" +
	"ShortenURL\x12\x1c.shortener.ShortenURLRequest\x1a\x1d.shortener.ShortenURLResponse\x12U\n" +
	"\x0eShortenURLJSON\x12 .shortener.ShortenURLJSONRequest\x1a!.shortener.ShortenURLJSONResponse\x12F\n" +
	"\tExpandURL\x12\x1b.shortener.ExpandURLRequest\x1a\x1c.shortener.ExpandURLResponse\x12O\n" +
	"\fShortenBatch\x12\x1e.shortener.ShortenBatchRequest\x1a\x1f.shortener.ShortenBatchResponse\x12L\n" +
	"\vGetUserURLs\x12\x1d.shortener.GetUserURLsRequest\x1a\x1e.shortener.GetUserURLsResponse\x12U\n" +
	"\x0eDeleteUserURLs\x12 .shortener.DeleteUserURLsRequest\x1a!.shortener.DeleteUserURLsResponse\x127\n" +
	"\x04Ping\x12\x16.shortener.PingRequest\x1a\x17.shortener.PingResponse\x12C\n" +
	"\bGetStats\x12\x1a.shortener.GetStatsRequest\x1a\x1b.shortener.GetStatsResponseB9Z7github.com/m-molecula741/shortener/internal/app/grpc/pbb\x06proto3"

var (
	file_proto_shortener_shortener_proto_rawDescOnce sync.Once
	file_proto_shortener_shortener_proto_rawDescData []byte
)

func file_proto_shortener_shortener_proto_rawDescGZIP() []byte {
	file_proto_shortener_shortener_proto_rawDescOnce.Do(func() {
		file_proto_shortener_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortener_shortener_proto_rawDesc), len(file_proto_shortener_shortener_proto_rawDesc)))
	})
	return file_proto_shortener_shortener_proto_rawDescData
}

var file_proto_shortener_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_shortener_shortener_proto_goTypes = []any{
	(*ShortenURLRequest)(nil),        // 0: shortener.ShortenURLRequest
	(*ShortenURLResponse)(nil),       // 1: shortener.ShortenURLResponse
	(*ShortenURLJSONRequest)(nil),    // 2: shortener.ShortenURLJSONRequest
	(*ShortenURLJSONResponse)(nil),   // 3: shortener.ShortenURLJSONResponse
	(*ExpandURLRequest)(nil),         // 4: shortener.ExpandURLRequest
	(*ExpandURLResponse)(nil),        // 5: shortener.ExpandURLResponse
	(*BatchShortenItem)(nil),         // 6: shortener.BatchShortenItem
	(*BatchShortenResponseItem)(nil), // 7: shortener.BatchShortenResponseItem
	(*ShortenBatchRequest)(nil),      // 8: shortener.ShortenBatchRequest
	(*ShortenBatchResponse)(nil),     // 9: shortener.ShortenBatchResponse
	(*UserURL)(nil),                  // 10: shortener.UserURL
	(*GetUserURLsRequest)(nil),       // 11: shortener.GetUserURLsRequest
	(*GetUserURLsResponse)(nil),      // 12: shortener.GetUserURLsResponse
	(*DeleteUserURLsRequest)(nil),    // 13: shortener.DeleteUserURLsRequest
	(*DeleteUserURLsResponse)(nil),   // 14: shortener.DeleteUserURLsResponse
	(*PingRequest)(nil),              // 15: shortener.PingRequest
	(*PingResponse)(nil),             // 16: shortener.PingResponse
	(*GetStatsRequest)(nil),          // 17: shortener.GetStatsRequest
	(*GetStatsResponse)(nil),         // 18: shortener.GetStatsResponse
}
var file_proto_shortener_shortener_proto_depIdxs = []int32{
	6,  // 0: shortener.ShortenBatchRequest.items:type_name -> shortener.BatchShortenItem
	7,  // 1: shortener.ShortenBatchResponse.items:type_name -> shortener.BatchShortenResponseItem
	10, // 2: shortener.GetUserURLsResponse.urls:type_name -> shortener.UserURL
	0,  // 3: shortener.URLShortener.ShortenURL:input_type -> shortener.ShortenURLRequest
	2,  // 4: shortener.URLShortener.ShortenURLJSON:input_type -> shortener.ShortenURLJSONRequest
	4,  // 5: shortener.URLShortener.ExpandURL:input_type -> shortener.ExpandURLRequest
	8,  // 6: shortener.URLShortener.ShortenBatch:input_type -> shortener.ShortenBatchRequest
	11, // 7: shortener.URLShortener.GetUserURLs:input_type -> shortener.GetUserURLsRequest
	13, // 8: shortener.URLShortener.DeleteUserURLs:input_type -> shortener.DeleteUserURLsRequest
	15, // 9: shortener.URLShortener.Ping:input_type -> shortener.PingRequest
	17, // 10: shortener.URLShortener.GetStats:input_type -> shortener.GetStatsRequest
	1,  // 11: shortener.URLShortener.ShortenURL:output_type -> shortener.ShortenURLResponse
	3,  // 12: shortener.URLShortener.ShortenURLJSON:output_type -> shortener.ShortenURLJSONResponse
	5,  // 13: shortener.URLShortener.ExpandURL:output_type -> shortener.ExpandURLResponse
	9,  // 14: shortener.URLShortener.ShortenBatch:output_type -> shortener.ShortenBatchResponse
	12, // 15: shortener.URLShortener.GetUserURLs:output_type -> shortener.GetUserURLsResponse
	14, // 16: shortener.URLShortener.DeleteUserURLs:output_type -> shortener.DeleteUserURLsResponse
	16, // 17: shortener.URLShortener.Ping:output_type -> shortener.PingResponse
	18, // 18: shortener.URLShortener.GetStats:output_type -> shortener.GetStatsResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_shortener_shortener_proto_init() }
func file_proto_shortener_shortener_proto_init() {
	if File_proto_shortener_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortener_shortener_proto_rawDesc), len(file_proto_shortener_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortener_shortener_proto_goTypes,
		DependencyIndexes: file_proto_shortener_shortener_proto_depIdxs,
		MessageInfos:      file_proto_shortener_shortener_proto_msgTypes,
	}.Build()
	File_proto_shortener_shortener_proto = out.File
	file_proto_shortener_shortener_proto_goTypes = nil
	file_proto_shortener_shortener_proto_depIdxs = nil
}
